config/routes.rb
Lilly::Application.routes.draw do
  resources :scouts do
    resources :advancements
    resources :service_hours
    match 'reqs', to: 'scouts#reqs', via: :put
  end

end

app/models/scout.rb
class Scout < ActiveRecord::Base
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  has_many :scout_advancements, :dependent => :destroy
  has_many :advancements, through: :scout_advancements

  has_many :scout_requirements, :dependent => :destroy
  has_many :requirements, through: :scout_requirements

  has_many :service_hours

  def full_name
    self.first_name + " " + self.last_name
  end
  def age
    now = Time.now.utc.to_date
    now.year - self.birthdate.year - (self.birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def as_json(options = { })
      # just in case someone says as_json(nil) and bypasses
      # our default...
      super((options || { }).merge({
          :methods => [:full_name, :age]
      }))
  end
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  include ScoutHelper
  before_action :set_scout, only: [:show, :edit, :update, :destroy]

  def index
    @scouts = Scout.all
  end

  def create
    Scout.new
  end

  def new
    @scout = Scout.new(:first_name => params[:first_name], :last_name => params[:last_name], :birthdate => params[:birthday])
    @scout.advancements << Rank.all
    Rank.all.each do |rank|
      @scout.requirements << rank.requirements
    end
    respond_to do |format|
      if @scout.save
        format.html { redirect_to @scout, notice: 'Scout was successfully created.' }
        format.json { render json: @scout, :status => :ok}
      else
        format.html { render action: 'new' }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @scout = set_scout
    respond_to do |format|
      format.html { render 'edit' }
      format.json {
        render :json => {
          :scout => @scout,
          :merit_badges => @scout.merit_badges
          } , :status => :ok
        }
      end
    end

    def destroy
      @scout.destroy
      respond_to do |format|
        format.html { redirect_to scouts_path }
        format.json { head :no_content }
      end
    end

    def show
      mb = MeritBadge.find_by_name(params[:badge])
      @scout.advancements << mb
      @scout.requirements << mb.requirements
      respond_to do |format|
        format.json {
          render :json => {
            :merit_badge => mb
            }, :status => :ok
          }
        end
      end

  def reqs
    result = get_updates
    respond_to do |format|
      format.json {
        render :json => {
          req_complete: result[:req_complete],
          parent_complete: result[:parent_complete]
          } , :status => :ok
        }
      end
  end

  def set_scout
    @scout = Scout.find(params[:id])
  end
end

app/helpers/scout_helper.rb
module ScoutHelper

  def get_updates
    ar = AdvancementRequirement.where(:requirement_id => params[:requirement_id]).first
    @sr = ScoutRequirement.where(:requirement_id => params[:requirement_id], :scout_id => params[:scout_id]).first
    result = Hash.new(false)
    if ar.isSolo?
      puts "SINGLE"
      result[:req_complete] = update_requirement(params[:requirement_id], @sr.isComplete?)
    elsif ar.isChild?
      puts "CHILD"
      result = update_child
    elsif ar.isParent?
      puts "PARENT"
    end
    result
  end

  def update_requirement(requirement_id, isComplete)
    puts "UPDATE REQ"
    puts requirement_id
    puts isComplete
    result = false
    if isComplete
      Scout.find(params[:scout_id]).scout_requirements.where(:requirement_id => requirement_id).first.update_attributes(:completed_date => nil)
    else
      Scout.find(params[:scout_id]).scout_requirements.where(:requirement_id => requirement_id).first.update_attributes(:completed_date => Date.today)
      result = true
    end
    update_reqs_remaining
    return result
  end

  def update_reqs_remaining
    ars = Scout.find(params[:scout_id]).advancements.find(params[:advancement_id]).advancement_requirements
    count = 0
    ars.each do |ar|
      if ar.isParent? || ar.isSolo?
        sr = ScoutRequirement.where(:requirement_id => ar.requirement_id, :scout_id => params[:scout_id])
        if sr.first.isComplete?
          count = count + 1
        end
      end
    end
    reqs_needed = get_reqs_needed
    reqs_remaining = reqs_needed - count
    if reqs_remaining == 0
      Scout.find(params[:scout_id]).scout_advancements.where(:advancement_id => params[:advancement_id]).first.update_attribute(:completed_date, Date.today)
      puts "ADVANCEMENT COMPLETE"
    else
      Scout.find(params[:scout_id]).scout_advancements.where(:advancement_id => params[:advancement_id]).first.update_attribute(:completed_date, nil)
      puts "NOT COMPLETE"
    end
    sa = Scout.find(params[:scout_id]).scout_advancements.where(:advancement_id => params[:advancement_id]).first.update_attribute(:reqs_remaining, reqs_remaining)
  end

  def get_reqs_needed
    ars = Scout.find(params[:scout_id]).advancements.find(params[:advancement_id]).advancement_requirements
    count = 0
    ars.each do |ar|
      if ar.isParent? || ar.isSolo?
        count = count + 1
      end
    end
    count
  end

  def update_child
    puts "UPDATE CHILD"
    result = Hash.new(false)
    result[:req_complete] = update_requirement(params[:requirement_id], @sr.isComplete?)
    result[:parent_complete] = update_parent
    return result
  end

  def update_parent
    parent_req = get_parent
    parent_finished = check_parent_finished(parent_req)
    puts "PARENT_FINISHED"
    puts parent_finished
    update_requirement(parent_req, !parent_finished)
  end

  def check_parent_finished(parent_req)
    children_needed = AdvancementRequirement.find(parent_req).children_count
    children_reqs = get_children(parent_req)
    count_children_complete = get_completed_children(children_reqs)
    count_children_complete >= children_needed
  end

  def get_children(parent_req)
    parent = AdvancementRequirement.find(parent_req)
    children_reqs = parent.children.split('#')
  end

  def get_parent
    AdvancementRequirement.find(params[:requirement_id]).parent
  end

  def get_completed_children(requirements)
    count = 0
    requirements.each do |requirement|
      req = Scout.find(params[:scout_id]).scout_requirements.where(:requirement_id => requirement).first
      if(req.completed_date != nil)
        count = count + 1
      end
    end
    count
  end
end

app/views/scouts/edit.html.erb
<div class="container">
  <h1 data-scout-id="<%= @scout.id %>"><%= @scout.full_name %></h1>
  <div id="advancements" class="hero-unit">
    <h2>Advancements</h2>
    <div class="empty">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Rank</th>
          </tr>
        </thead>
        <tbody>
          <% @scout.advancements.ranks.each do |rank|%>
          <tr data-link="<%= edit_scout_advancement_path(@scout, rank) %>">
            <td><%= rank.name %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div id="merit_badges" class="hero-unit">
    <h2>Merit Badges</h2>
    <% if @scout.advancements.merit_badges.count == 0 %>
    <div class="empty">Boo, no merit badges yet</div>
    <% else %>
    <div class="empty">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
            </th>
            <th>
              Name
            </th>
            <th>
             Requirements to Complete Advancement
           </th>
         </tr>
       </thead>
       <tbody>
        <% @scout.advancements.merit_badges.each do |badge|%>
        <tr data-link="<%= edit_scout_advancement_path(@scout, badge) %>">
          <td>
            <% if badge.eagle_required == true %>
            <i class="icon-ok"></i>
            <% end %>
          </td>
          <td><%= badge.name %></td>
          <td><%= @scout.scout_advancements.where(:advancement_id => badge.id).first.reqs_remaining %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
  <a href="#" class="btn btn-success" id="add_merit_badge">Add</a>
</div>
<div id="service_hours_table" class="hero-unit">
  <h2>Service Hours</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Place</th>
        <th>Date</th>
        <th>Hours</th>
      </tr>
    </thead>
    <tbody>
      <% @scout.service_hours.each do |hour| %>
      <tr>
        <td><%= hour.title %></td>
        <td><%= hour.place %></td>
        <td><%= hour.date_of_service %></td>
        <td><%= hour.minutes/60.0 %></td>
      </tr>
      <% end %>
    </tbody>
  <table>
  <a href="#" class="btn btn-success" id="add_service_hours">Add</a>
</div>
<%= button_to 'Remove Scout', @scout, :method => :delete, :class => "btn btn-warning", data: { confirm: 'Are you sure?' }%>
</div>

app/views/scouts/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <button type="button" class="btn btn-primary" id="add_new_scout">Add Scout</button>
      <table class="table table-striped" id="main_scout_list">
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
          </tr>
        </thead>
        <tbody>
          <% @scouts.each do |scout| %>
          <tr data-link="<%= edit_scout_path(scout) %>">
            <td><%= scout.full_name %></td>
            <td><%= scout.age %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>