config/routes.rb
Lilly::Application.routes.draw do
  resources :scouts do
    resources :advancements
    resources :service_hours
    match 'reqs', to: 'scouts#reqs', via: :put
  end

end

app/models/advancement.rb
class Advancement < ActiveRecord::Base
  has_many :scout_advancements, :dependent => :destroy
  has_many :scouts, through: :scout_advancements

  has_many :advancement_requirements, :dependent => :destroy
  has_many :requirements, through: :advancement_requirements

  # scope :ranks, -> { where(:type => "Rank").order(ordinal: :asc)}
  scope :ranks, -> { where(:type => "Rank")}
  scope :merit_badges, -> { where(:type => "MeritBadge").order(name: :asc)}
  scope :alpha, -> { order(name: :asc) }
end

app/controllers/advancements_controller.rb
class AdvancementsController < ApplicationController
  def edit
    @scout = set_scout
    @advancement = set_advancement
  end

  def destroy
    @scout = set_scout
    @mb = MeritBadge.find_by_id(params[:id])
    @requirements = MeritBadge.find_by_id(params[:id]).requirements
    @scout.advancements.delete(@mb)
    @scout.requirements.delete(@requirements)
    respond_to do |format|
      format.html { redirect_to edit_scout_path(Scout.find_by_id(params[:scout_id])) }
      format.json { head :no_content }
    end
  end

  def set_advancement
    @scout = set_scout
    @advancement = @scout.advancements.find_by_id(params[:id])
  end

  def set_scout
    @scout = Scout.find(params[:scout_id])
  end
end

app/views/advancements/_requirement.html.erb
<div class="row" data-req="<%= req.requirement_id %>" data-children="<%= req.children %>" data-parent="<%= req.parent %>", data-childrenCount="<%= req.children_count %>">
  <% if req.label != nil && req.label.is_number? %>
  <div class="cell">
    <%= req.label %>.
  </div>
  <% elsif req.label != nil && req.label.is_letter? %>
  <div class="cell letter">
    <%= req.label %>
  </div>
  <% else req.label == nil%>
  <div class="cell sub-letter">
    <%= req.label %>
  </div>
  <% end %>
  <div class="cell">
    <%= req.requirement.requirement %>
  </div>
  <div>
    <% if @scout.scout_requirements.where(:requirement_id => req.requirement_id)[0].completed_date != nil %>
    <%= image_tag("checkmark.png", size: "48x48") %>
    <% end %>
  </div>
</div>

app/views/advancements/_requirement_mb.html.erb
<% num.times do |n| %>
<div class="row">
  <div class="cell"></div>
  <div class="cell">
    <select class="chzn-select" id="chzn-select">
      <% MeritBadge.alpha.all.each do |mb| %>
      <option><%= mb.name %></option>
      <% end %>
    </select>
  </div>
  <div class="cell"></div>
</div>
<% end %>

app/views/advancements/edit.html.erb
<h1><%= @advancement.name %></h1>
<%= button_to 'Go Back', edit_scout_path(@scout), :method => :get, :class => "btn btn-primary" %>
<div class="container">
  <div class="table" data-scout="<%= params[:scout_id] %>" data-advancement="<%= params[:id] %>">
    <% @advancement.advancement_requirements.order('ord asc').each do |req| %>
      <% if req.requirement.children_merit_badge_count == 0 %>
        <%= render :partial => 'requirement', :locals => { :req => req } %>
      <% else %>
        <%= render :partial => 'requirement', :locals => { :req => req } %>
        <%= render :partial => 'requirement_mb', :locals => { :num => req.requirement.children_merit_badge_count } %>
      <% end %>
    <% end %>
  </div>
</div>
<% if @advancement.type == "MeritBadge" %>
<%= button_to 'Delete Merit Badge', scout_advancement_path(@scout, @advancement), :method => :delete, :class => "btn btn-warning", data: { confirm: 'Are you sure?' }%>
<% end %>